### PR TITLE
Null erewee3 spr3 4 closes #66

### LINKED ISSUE #66: TEAM NULL: Implementing ACL Drop
Implement detection for packets that are denied by access lists.

More info: https://www.petenetlive.com/KB/Article/0001108

### PR DESCRIPTION
**Pull request by ereewa3**

### CODE REVIEW

**Comment by claesmk** [comment]
Some others on your team have already committed their code to the branch, so you need to sync your fork to upstream/null_ids - same way we've done in the past.

**Comment by ereewa3** [comment]
After syncing my fork my 1 of my tests fail at:

**Comment by ereewa3** [comment]
And here: 
image

Not sure why, after merging I just added in my work into the parse file.

**Comment by claesmk** [comment]
@ereewa3 Were you able to fix the indents on the 4 lines of code shown in the comments above?  After that I think everything will work OK.

**Comment by ereewa3** [comment]
Yes, I reformatted it but one test keeps failing. I have updated my fork.

**Comment by claesmk** [comment]
You need to un-indent this part of your code, then it will work OK.  Right now they way you have it is like this:
```
if rec['ID'] == 713162:
    if m:
        ...
    if rec['ID'] == 733100:
    if m:
        ...
```

The checks for the ID need to be on the same level like this:
```
if rec['ID'] == 713162:
    if m:
        ...
if rec['ID'] == 733100:
   if m:
       ...
```
     
image

**Comment by ereewa3** [comment]
Made those changes, all the tests pass now!

**Pull request merged**
